Repository uselagoon/lagoon, pull requests merged in 2019-09, with the labels that each got.

#1074 Multiple openshift versions in CI
  Jenkinsfile
  Makefile
  local-dev/api-data/01-populate-api-data.gql
Labels: work in progress

#1215 Adding end of life notification for node
  images/node/Dockerfile
Labels: lifecycle

#1245 rbac doc changes #1237
  docs/administering_lagoon/create-project.gql
  docs/administering_lagoon/graphql_api.md
  docs/administering_lagoon/rbac.md
  docs/index.md
  mkdocs.yml
Labels: documentation
