Repository uselagoon/lagoon, pull requests merged in 2019-11, with the labels that each got.

#1390 Fluentd prometheus plugin fix
  services/logs-forwarder/Dockerfile
Labels: Logging

#1392 Removing fluentd prometheus plugin version constraint.
  services/logs-forwarder/Dockerfile
Labels: Logging

#1277 Fixed remote-shell examples
  docs/using_lagoon/remote_shell.md
Labels: ready-for-release

#1165 UI Deployments Improvements
  services/api/src/resolvers.js
  services/api/src/resources/deployment/helpers.js
  services/api/src/resources/deployment/resolvers.js
  services/api/src/resources/deployment/sql.js
  services/api/src/typeDefs.js
  services/keycloak/start.sh
  services/openshiftmisc/src/handlers/openshiftBuildCancel.js
  services/openshiftmisc/src/index.js
  services/ui/src/components/AddTask/components/DrushArchiveDump.js
  services/ui/src/components/AddTask/components/DrushCacheClear.js
  services/ui/src/components/AddTask/components/DrushRsyncFiles.js
  services/ui/src/components/AddTask/components/DrushSqlDump.js
  services/ui/src/components/AddTask/components/DrushSqlSync.js
  services/ui/src/components/Backups/index.js
  services/ui/src/components/Button/ButtonAction.js
  services/ui/src/components/Button/ButtonLink.js
  services/ui/src/components/Button/ButtonStyles.js
  services/ui/src/components/CancelDeployment/index.js
  services/ui/src/components/DeleteConfirm/index.js
  services/ui/src/components/DeployLatest/index.js
  services/ui/src/components/Deployment/index.js
  services/ui/src/components/Environments/index.js
  services/ui/src/components/RestoreButton/Prepare.js
  services/ui/src/components/RestoreButton/index.js
  services/ui/src/lib/query/EnvironmentWithDeployments.js
Labels: ready-for-release

#1147 Adding the DeleteSshKeyById API endpoint.
  node-packages/commons/src/api.js
  services/api-db/docker-entrypoint-initdb.d/03-procedures.sql
  services/api/src/resolvers.js
  services/api/src/resources/sshKey/resolvers.js
  services/api/src/typeDefs.js
Labels: ready-for-release

#1158 Update version of oc used in oc image
  images/oc/Dockerfile
Labels: work in progress

#1355 Use KVM as the minishift vm-driver on Linux
  Makefile
  docs/developing_lagoon/index.md
Labels: testing

#1356 Fix deploymentconfig test
  services/ssh/home/rsh.sh
Labels: testing
