Repository uselagoon/lagoon, pull requests merged in 2019-12, with the labels that each got.

#1399 Add Lagoon favicon. Fixes #1305
  services/ui/server.js
  services/ui/src/components/Favicon/index.js
  services/ui/src/pages/_app.js
  services/ui/src/static/images/favicons/apple-touch-icon.png
  services/ui/src/static/images/favicons/favicon-16x16.png
  services/ui/src/static/images/favicons/favicon-32x32.png
  services/ui/src/static/images/favicons/favicon.ico
Labels: ready-for-release

#1354 Fix some typos and .PHONY targets
  Makefile
Labels: testing

#1444 Update PHP7 versions supported and tested.
  docs/using_lagoon/docker_images/php-fpm.md
  docs/using_lagoon/drupal/drupal7-mariadb/cli.dockerfile
  docs/using_lagoon/drupal/drupal7-mariadb/php.dockerfile
  docs/using_lagoon/index.md
  images/php/cli/Dockerfile
  tests/files/drupal8-dockerfiles/php7.4/builder.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/mariadb.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/nginx.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/php.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/postgres.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/redis.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/solr.dockerfile
  tests/files/drupal8-dockerfiles/php7.4/varnish.dockerfile
  tests/tests/drupal.yaml
Labels: testing

#1350 Add logs-db-service alias for logs-db when running locally
  docker-compose.yaml
Labels: testing

#1396 API Automated Billing Calculations
  .prettierrc
  .vscode/launch.json
  .vscode/settings.json
  docs/developing_lagoon/api-debugging.md
  docs/developing_lagoon/index.md
  local-dev/api-data/01-populate-api-data.gql
  node-packages/eslint-config-lagoon-node/index.js
  services/api-db/docker-entrypoint-initdb.d/00-tables.sql
  services/api-db/docker-entrypoint-initdb.d/01-migrations.sql
  services/api-db/docker-entrypoint-initdb.d/03-procedures.sql
  services/api/.vscode/launch.json
  services/api/jest.config.js
  services/api/package.json
  services/api/src/apolloServer.js
  services/api/src/clients/sqlClient.js
  services/api/src/clients/sqlClient.ts
  services/api/src/helpers/billingGroups.ts
  services/api/src/helpers/sync-groups-opendistro-security.ts
  services/api/src/models/environment.ts
  services/api/src/models/group.ts
  services/api/src/models/project.ts
  services/api/src/resolvers.js
  services/api/src/resources/billing/billingCalculations.test.ts
  services/api/src/resources/billing/billingCalculations.ts
  services/api/src/resources/billing/helpers.ts
  services/api/src/resources/billing/pricing.ts
  services/api/src/resources/environment/resolvers.js
  services/api/src/resources/group/gql.test.ts
  services/api/src/resources/group/resolvers.test.ts
  services/api/src/resources/group/resolvers.ts
  services/api/src/resources/project/helpers.js
  services/api/src/resources/project/resolvers.js
  services/api/src/resources/project/sql.js
  services/api/src/typeDefs.js
  tsconfig.json
  yarn.lock
Labels: work in progress

#1269 Harbor Integration
  .env.defaults
  .lagoon.harbor-secrets.yaml
  .lagoon.yml
  Makefile
  docker-compose.yaml
  docs/using_lagoon/docker_images/postgres.md
  images/harbor-clair/Dockerfile
  images/harbor-clair/docker-entrypoint.sh
  images/harbor-core/Dockerfile
  images/harbor-core/entrypoint.sh
  images/harbor-database/Dockerfile
  images/harbor-database/docker-entrypoint-initdb.d/initial-registry.sql
  images/harbor-jobservice/Dockerfile
  images/harbor-nginx/Dockerfile
  images/harbor-nginx/nginx.conf
  images/harbor-portal/Dockerfile
  images/harbor-redis/Dockerfile
  images/harbor-registry/Dockerfile
  images/harbor-registry/entrypoint.sh
  images/harbor-registryctl/Dockerfile
  images/harbor-registryctl/start.sh
  lagoon-remote/docker-compose.yaml
  lagoon-remote/harbor-clair
  lagoon-remote/harbor-core
  lagoon-remote/harbor-database
  lagoon-remote/harbor-jobservice
  lagoon-remote/harbor-nginx
  lagoon-remote/harbor-portal
  lagoon-remote/harbor-redis
  lagoon-remote/harborregistry
  lagoon-remote/harborregistryctl
  services/harbor-clair/Dockerfile
  services/harbor-clair/docker-entrypoint.sh
  services/harbor-clair/harbor-clair.yml
  services/harbor-core/Dockerfile
  services/harbor-core/entrypoint.sh
  services/harbor-core/harbor-core.yml
  services/harbor-database/Dockerfile
  services/harbor-database/docker-entrypoint-initdb.d/initial-registry.sql
  services/harbor-database/harbor-database.yml
  services/harbor-jobservice/Dockerfile
  services/harbor-jobservice/harbor-jobservice.yml
  services/harbor-nginx/Dockerfile
  services/harbor-nginx/harbor-nginx.yml
  services/harbor-nginx/nginx.conf
  services/harbor-portal/Dockerfile
  services/harbor-portal/harbor-portal.yml
  services/harbor-redis/Dockerfile
  services/harbor-redis/harbor-redis.yml
  services/harborregistry/Dockerfile
  services/harborregistry/entrypoint.sh
  services/harborregistry/harborregistry.yml
  services/harborregistryctl/Dockerfile
  services/harborregistryctl/harborregistry.yml
  services/harborregistryctl/start.sh
Labels: work in progress

#1490 Documentation work
  docs/administering_lagoon/graphql_api.md
  docs/using_lagoon/environment_variables.md
Labels: documentation, ready-for-release
