Repository uselagoon/lagoon, pull requests merged in 2020-12, with the labels that each got.

#2354 AIOAB-29 Filter out ACME challenges from hit data
  services/api/src/models/environment.ts
Labels: 8-automation-helpers

#1641 Add helmchart for python
  Makefile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/python/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/python/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/python/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/values.yaml
  local-dev/api-data/03-populate-api-data-kubernetes.gql
  local-dev/api-data/04-populate-api-data-controller.gql
  local-dev/git/Dockerfile
  tests/files/python3.7/.lagoon.yml
  tests/files/python3.7/Dockerfile
  tests/files/python3.7/app.py
  tests/files/python3.7/docker-compose.yml
  tests/tests/python.yaml
  tests/tests/python/deploy-branch.yaml
  tests/tests/python/deploy-pullrequest.yaml
  tests/tests/python/push.yaml
Labels: 0-kubernetes

#2355 BaaS bucket name override support
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/templates/schedule.yaml
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/backup-schedule.yml
Labels: 2-build-deploy

#2351 Make the prebackuppod wait until the backup completes
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch-cluster/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-dbaas/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-shared/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mongo/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/postgres/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq-cluster/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/redis-persistent/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/solr/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/varnish-persistent/prebackuppod.yml
Labels: 8-automation-helpers

#2350 implement promote feature with k8s
  Makefile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-promote.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-tag.sh
  local-dev/api-data/03-populate-api-data-kubernetes.gql
  node-packages/commons/src/tasks.ts
  services/kubernetesbuilddeploy/src/index.ts
  tests/checks/check-branch-sha.yaml
  tests/tests/features-kubernetes.yaml
  tests/tests/features/promote.yaml
Labels: 2-build-deploy

#2362 less confusing naming of helmcharts
  Makefile
Labels: 8-automation-helpers

#2363 disable testing for now
  Jenkinsfile
Labels: skip-changelog

#2365 remove s3-save and s3-load
  Jenkinsfile
  Makefile
Labels: 2-build-deploy

#2366 pull images via imagecache
  local-dev/k3d-registries.yaml
Labels: skip-changelog

#2330 Active Standby Button Fix
  services/ui/src/components/ActiveStandbyConfirm/index.js
Labels: bug

#1647 Postgres Helmchart
  Makefile
  docker-compose.yaml
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/templates/dbaas.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/values.yaml
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-postgres-dbaas.sh
  local-dev/helm-values-postgresqlprovider.yml
  local-dev/postgresql-dbaas-provider/Dockerfile
  tests/files/drupal8-postgres-single/.dockerignore
  tests/files/drupal8-postgres-single/.gitignore
  tests/files/drupal8-postgres-single/.lagoon.yml
  tests/files/drupal8-postgres-single/LICENSE
  tests/files/drupal8-postgres-single/README.md
  tests/files/drupal8-postgres-single/composer.json
  tests/files/drupal8-postgres-single/composer.lock
  tests/files/drupal8-postgres-single/config/sync/.gitkeep
  tests/files/drupal8-postgres-single/docker-compose.yml
  tests/files/drupal8-postgres-single/drupal-postgres.sql.gz
  tests/files/drupal8-postgres-single/drush/README.md
  tests/files/drupal8-postgres-single/drush/aliases.drushrc.php
  tests/files/drupal8-postgres-single/drush/drushrc.php
  tests/files/drupal8-postgres-single/drush/policy.drush.inc
  tests/files/drupal8-postgres-single/scripts/composer/ScriptHandler.php
  tests/files/drupal8-postgres-single/web/.csslintrc
  tests/files/drupal8-postgres-single/web/.editorconfig
  tests/files/drupal8-postgres-single/web/.eslintignore
  tests/files/drupal8-postgres-single/web/.gitattributes
  tests/files/drupal8-postgres-single/web/.ht.router.php
  tests/files/drupal8-postgres-single/web/.htaccess
  tests/files/drupal8-postgres-single/web/autoload.php
  tests/files/drupal8-postgres-single/web/index.php
  tests/files/drupal8-postgres-single/web/modules/.gitkeep
  tests/files/drupal8-postgres-single/web/profiles/.gitkeep
  tests/files/drupal8-postgres-single/web/robots.txt
  tests/files/drupal8-postgres-single/web/sites/default/all.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/all.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/default.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/default.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/development.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/development.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/example.settings.local.php
  tests/files/drupal8-postgres-single/web/sites/default/production.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/production.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/settings.php
  tests/files/drupal8-postgres-single/web/sites/example.sites.php
  tests/files/drupal8-postgres-single/web/themes/.gitkeep
  tests/files/drupal8-postgres-single/web/update.php
  tests/files/drupal8-postgres-single/web/web.config
  tests/tests/drupal-postgres.yaml
Labels: 0-kubernetes

#2370 Remove failing postgres-drupal tests from Openshift
  Makefile
Labels: 6-images-testing

#2369 Restore some logging services
  services/logs-concentrator/Dockerfile
  services/logs-concentrator/entrypoint.sh
  services/logs-concentrator/fluent.conf
  services/logs-dispatcher/Dockerfile
  services/logs-dispatcher/entrypoint.sh
  services/logs-dispatcher/fluent.conf
  services/logs-tee/Dockerfile
  services/logs-tee/entrypoint.sh
Labels: 3-logging-reporting

#2345 Harbor via helm
  .env.defaults
  Makefile
  docker-compose.yaml
  images/docker-host/Dockerfile
  local-dev/api-data-watcher-pusher/api-data/03-populate-api-data-kubernetes.gql
  local-dev/helm-values-harbor.yml
  local-dev/k3d-nginx-ingress.yaml
  local-dev/k3d-registries.yaml
  services/api/Dockerfile
  services/api/src/clients/harborClient.js
  services/api/src/migrations/2-harbor/harborSync.ts
  services/api/src/resources/project/harborSetup.ts
  services/harbor-core/0015_1.10.0_schema.up.sql
  services/harbor-core/Dockerfile
  services/harbor-core/ci-secret.key
  services/harbor-core/ci_tls.crt
  services/harbor-core/ci_tls.key
  services/harbor-core/entrypoint.sh
  services/harbor-core/harbor-core.yml
  services/harbor-core/harbor-core_ci.conf.yaml
  services/harbor-database/Dockerfile
  services/harbor-database/docker-entrypoint-initdb.d/initial-registry.sql
  services/harbor-database/harbor-database.yml
  services/harbor-jobservice/Dockerfile
  services/harbor-jobservice/ci-config.yaml
  services/harbor-jobservice/harbor-jobservice.yml
  services/harbor-nginx/Dockerfile
  services/harbor-nginx/ci.nginx.conf
  services/harbor-nginx/harbor-nginx.yml
  services/harbor-nginx/nginx.conf
  services/harbor-portal/Dockerfile
  services/harbor-portal/harbor-portal.yml
  services/harbor-redis/Dockerfile
  services/harbor-redis/harbor-redis.yml
  services/harbor-trivy/Dockerfile
  services/harbor-trivy/entrypoint.sh
  services/harbor-trivy/harbor-trivy.yml
  services/harbor-trivy/install_cert.sh
  services/harborregistry/Dockerfile
  services/harborregistry/entrypoint.sh
  services/harborregistry/harborregistry.yml
  services/harborregistry/install_cert.sh
  services/harborregistry/registry_ci.cfg.yaml
  services/harborregistryctl/Dockerfile
  services/harborregistryctl/harborregistry.yml
  services/harborregistryctl/install_cert.sh
  services/harborregistryctl/registryctl_ci.cfg.yaml
  services/harborregistryctl/start.sh
  tests/tests/features/ingress-annotations.yaml
  tests/tests/features/namespace-labels.yaml
Labels: 6-images-testing, 8-automation-helpers

#2284 install rabbitmq_prometheus for monitoring
  images/rabbitmq-cluster/enabled_plugins
  images/rabbitmq/Dockerfile
Labels: 4-metrics-alerting

#2324 Add Kubernetes to API
  services/api/src/resolvers.js
  services/api/src/resources/environment/helpers.ts
  services/api/src/resources/environment/resolvers.ts
  services/api/src/resources/project/helpers.ts
  services/api/src/resources/project/resolvers.ts
  services/api/src/typeDefs.js
Labels: 1-api-auth, Lagoon2.0

#2380 fix broken DBAAS_ENVIRONMENT override system
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy

#2383 add exclusion for http_request on acme-challenge
  services/api/src/models/environment.ts
Labels: 10-admin-user-interfaces

#2367 Get CI running using helm charts
  .gitignore
  Jenkinsfile
  Makefile
  local-dev/api-data-watcher-pusher/api-data/03-populate-api-data-kubernetes.gql
  tests/tests/active-standby/deploy-active-standby.yaml
Labels: 6-images-testing, Lagoon2.0

#2311 initial add of postgres helmchart to lagoon 2.x/main
  Makefile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/templates/dbaas.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/values.yaml
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-postgres-dbaas.sh
  tests/files/drupal8-postgres-single/.dockerignore
  tests/files/drupal8-postgres-single/.gitignore
  tests/files/drupal8-postgres-single/.lagoon.yml
  tests/files/drupal8-postgres-single/LICENSE
  tests/files/drupal8-postgres-single/composer.json
  tests/files/drupal8-postgres-single/composer.lock
  tests/files/drupal8-postgres-single/config/sync/.gitkeep
  tests/files/drupal8-postgres-single/docker-compose.yml
  tests/files/drupal8-postgres-single/drupal-postgres.sql.gz
  tests/files/drupal8-postgres-single/drush/aliases.drushrc.php
  tests/files/drupal8-postgres-single/drush/drushrc.php
  tests/files/drupal8-postgres-single/drush/policy.drush.inc
  tests/files/drupal8-postgres-single/scripts/composer/ScriptHandler.php
  tests/files/drupal8-postgres-single/web/.csslintrc
  tests/files/drupal8-postgres-single/web/.editorconfig
  tests/files/drupal8-postgres-single/web/.eslintignore
  tests/files/drupal8-postgres-single/web/.gitattributes
  tests/files/drupal8-postgres-single/web/.ht.router.php
  tests/files/drupal8-postgres-single/web/.htaccess
  tests/files/drupal8-postgres-single/web/autoload.php
  tests/files/drupal8-postgres-single/web/index.php
  tests/files/drupal8-postgres-single/web/modules/.gitkeep
  tests/files/drupal8-postgres-single/web/profiles/.gitkeep
  tests/files/drupal8-postgres-single/web/robots.txt
  tests/files/drupal8-postgres-single/web/sites/default/all.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/all.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/default.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/default.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/development.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/development.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/example.settings.local.php
  tests/files/drupal8-postgres-single/web/sites/default/production.services.yml
  tests/files/drupal8-postgres-single/web/sites/default/production.settings.php
  tests/files/drupal8-postgres-single/web/sites/default/settings.php
  tests/files/drupal8-postgres-single/web/sites/example.sites.php
  tests/files/drupal8-postgres-single/web/themes/.gitkeep
  tests/files/drupal8-postgres-single/web/update.php
  tests/files/drupal8-postgres-single/web/web.config
  tests/tests/drupal-postgres.yaml
Labels: 0-kubernetes

#2391 Add python helmchart & test to Lagoon 2
  Makefile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/python/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/python/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/python/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/values.yaml
  local-dev/api-data-watcher-pusher/api-data/03-populate-api-data-kubernetes.gql
  local-dev/git/Dockerfile
  tests/files/python3.7/.lagoon.yml
  tests/files/python3.7/Dockerfile
  tests/files/python3.7/app.py
  tests/files/python3.7/docker-compose.yml
  tests/tests/python.yaml
  tests/tests/python/deploy-branch.yaml
  tests/tests/python/deploy-pullrequest.yaml
  tests/tests/python/push.yaml
Labels: 0-kubernetes

#2374 Only monitor first route/ingress
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 8-automation-helpers

#2397 Only monitor first ingress (PR2374)
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 0-kubernetes

#2389 upgrading rabbitmq delayed message exchange plugin to 3.8.9
  images/rabbitmq/Dockerfile
  images/rabbitmq/rabbitmq_delayed_message_exchange-3.8.0.ez
  images/rabbitmq/rabbitmq_delayed_message_exchange-3.8.9.ez
Labels: 2-build-deploy

#2390 Rabbitmq master updates
  images/rabbitmq/Dockerfile
  images/rabbitmq/rabbitmq_delayed_message_exchange-3.8.0.ez
  images/rabbitmq/rabbitmq_delayed_message_exchange-3.8.9.ez
Labels: 2-build-deploy

#2385 Use the lastTransitionTime for failed kubernetes build jobs
  services/kubernetesbuilddeploymonitor/src/index.ts
Labels: 2-build-deploy

#2375 Push the .lagoon.yml file into a configmap
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy

#2368 add update-images.sh for docker-host
  images/docker-host/Dockerfile
  images/docker-host/update-images.sh
Labels: 2-build-deploy

#2406 fix persistentStorage.name in prebackuppods
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
Labels: 2-build-deploy

#2405 Remove unused osControllerX systems
  node-packages/commons/src/tasks.ts
Labels: skip-changelog

#2404 Adding Support for BaasBucketName to Snapshot Restore Functionality
  node-packages/commons/src/tasks.ts
  services/kubernetesmisc/src/handlers/resticRestore.ts
  services/openshiftmisc/src/handlers/resticRestore.ts
Labels: 8-automation-helpers

#2408 Set an error so active-standby task retries
  taskimages/activestandby/main.go
Labels: 2-build-deploy

#2411 Update to latest releases of DBaaS and Dioscuri
  Makefile
  openshift-setup/dbaas-operator.yaml
  openshift-setup/dioscuri-operator.yaml
Labels: skip-changelog

#2412 Add test to check that the API is updated after an active/standby switch
  tests/tests/active-standby/deploy-active-standby.yaml
Labels: skip-changelog

#2409 readd logs-concentrator, dispatcher, tee images to makefile and build
  Makefile
Labels: 6-images-testing

#2407 Use controllers to decide buildimage (PR2216)
  node-packages/commons/src/tasks.ts
Labels: 2-build-deploy

#2418 Update helm chart repos in CI
  Makefile
Labels: 6-images-testing

#2415 Consolidated Lagoon 1.13 Pull Requests
  Makefile
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
  node-packages/commons/src/tasks.ts
  taskimages/activestandby/main.go
  tests/tests/active-standby/deploy-active-standby.yaml
Labels: Lagoon2.0

#2414 More Lagoon 2 cleanup
  .env.defaults
  Jenkinsfile.end2end
  Makefile
  charts/dbaas-operator.yaml
  charts/dbaas-providers.yaml
  charts/role-mariadb-operator.yaml
Labels: skip-changelog

#2417 Use the latest build-deploy controller and update active-standby task to use patch
  Makefile
  go.mod
  openshift-setup/lagoon-builddeploy-controller.yml
  taskimages/activestandby/main.go
Labels: 2-build-deploy

#2413 Cleanup lagoon_openshiftBuildDeploy lagoon_kubernetesBuildDeploy
  local-dev/api-data-watcher-pusher/api-data/03-populate-api-data-kubernetes.gql
  node-packages/commons/src/tasks.ts
  services/api-db/docker-entrypoint-initdb.d/01-migrations.sql
  services/api/src/mocks.js
  services/api/src/typeDefs.js
Labels: 2-build-deploy

#2198 Add Gitea-specific webhook
  services/webhook-handler/README.md
  services/webhook-handler/src/extractWebhookData.ts
  services/webhook-handler/src/types.ts
  services/webhooks2tasks/src/handlers/giteaBranchDeleted.ts
  services/webhooks2tasks/src/handlers/giteaPullRequestClosed.ts
  services/webhooks2tasks/src/handlers/giteaPullRequestOpened.ts
  services/webhooks2tasks/src/handlers/giteaPullRequestSynchronize.ts
  services/webhooks2tasks/src/handlers/giteaPush.ts
  services/webhooks2tasks/src/webhooks/projects.ts
Labels: 2-build-deploy

#2419 Fix storage-calculator so it can be used for kubernetes and openshift projects
  services/storage-calculator/Dockerfile
  services/storage-calculator/calculate-storage.sh
Labels: 0-kubernetes, 4-metrics-alerting

#2223 Fix #2222 by adding LAGOON_ENVIRONMENT variable
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/configmap.yml
Labels: 2-build-deploy

#2423 Give a little more testing time, up to 5min.
  tests/checks/check-ingress-annotations.yaml
  tests/checks/check-namespace-labels.yaml
  tests/checks/check-url-header.yaml
  tests/checks/check-url-redirect-host.yaml
  tests/checks/check-url-redirect.yaml
  tests/checks/check-url-returncode-host.yaml
  tests/checks/check-url-returncode.yaml
  tests/tasks/ssh/ssh-command.yaml
  tests/tests/active-standby/deploy-active-standby.yaml
Labels: 6-images-testing

#2420 cleanup kubectl-build-deploy-dind:
  images/kubectl-build-deploy-dind/Dockerfile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/build-deploy.sh
  images/kubectl-build-deploy-dind/scripts/exec-additional-yaml.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-create-pvc.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-create-servicebroker.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-resources.sh
  images/kubectl-build-deploy-dind/scripts/exec-monitor-daemonset.sh
  images/kubectl-build-deploy-dind/scripts/exec-monitor-statefulset.sh
  images/kubectl-build-deploy-dind/scripts/exec-push-parallel-tug.sh
  images/kubectl-build-deploy-dind/tug.sh
  images/kubectl-build-deploy-dind/tug/Dockerfile
  images/kubectl-build-deploy-dind/tug/tug-build-push.sh
Labels: 2-build-deploy

#2422 Backport #2419 Fix storage-calculator so it can be used for kubernetes and openshift projects
  services/storage-calculator/Dockerfile
  services/storage-calculator/calculate-storage.sh
Labels: 0-kubernetes, 4-metrics-alerting

#2421 Fix #2222 by adding LAGOON_ENVIRONMENT variable
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/configmap.yml
Labels: 2-build-deploy

#2427 move annotations for backups into pods
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
Labels: 2-build-deploy, 8-automation-helpers

#2430 update to new k8up annotations for kubernetes clusters
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/pvc.yaml
Labels: 2-build-deploy, 8-automation-helpers

#2431 backup-handler: also match mariadb-single
  services/backup-handler/internal/handler/main.go
Labels: 8-automation-helpers

#2433 pick #1991 into getControllerBuildData
  node-packages/commons/src/tasks.ts
Labels: 2-build-deploy

#2432 allow to update activeSystemsPromote via updateProject
  services/api/src/resources/project/resolvers.ts
  services/api/src/typeDefs.js
Labels: 1-api-auth
