Repository uselagoon/lagoon, pull requests merged in 2020-11, with the labels that each got.

#2294 Wraps OS login in an "if" to prevent build breaking on error
  images/oc-build-deploy-dind/build-deploy.sh
Labels: 2-build-deploy

#2300 Use image cache and harbor for public images in kubernetes
  images/kubectl-build-deploy-dind/Dockerfile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-copy-to-registry.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-tag-dockerhub.sh
Labels: 2-build-deploy, hacktoberfest-accepted

#2299 Use amazee.io docker image cache for prebackuppod images
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch-cluster/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-dbaas/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-shared/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mongo/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/postgres/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq-cluster/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/redis-persistent/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/solr/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/varnish-persistent/prebackuppod.yml
Labels: 2-build-deploy, skip-changelog

#2286 add :latest tag to amazeeio base/task image push
  Makefile
Labels: 6-images-testing

#2292 Re-add local-minio to main-test-services
  Makefile
Labels: 6-images-testing

#2304 docker-host with registry-mirror
  images/docker-host/Dockerfile
Labels: 2-build-deploy

#2305 prefix library images with library/
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy

#2301 Use image cache and harbor for public images in openshift
  images/oc-build-deploy-dind/Dockerfile
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/scripts/exec-openshift-copy-to-registry.sh
  images/oc-build-deploy-dind/scripts/exec-openshift-tag-dockerhub.sh
  images/oc/Dockerfile
Labels: 2-build-deploy, hacktoberfest-accepted

#2306 Do not handle images for shared services
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/mariadb-dbaas/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-shared/prebackuppod.yml
Labels: 2-build-deploy

#2308 Adds conditional check when running add_metadata_to_project
  services/api-db/docker-entrypoint-initdb.d/01-migrations.sql
Labels: bug

#2337 Fix test for ingress-nginx compatibility
  tests/tests/nginx/check-first.yaml
  tests/tests/nginx/check-second.yaml
Labels: 6-images-testing

#2347 Update drupal test fixtures to support running tests via helm
  tests/files/drupal8-mariadb-single/.lagoon.yml
  tests/files/drupal8-mariadb-single/drush/aliases.drushrc.php
  tests/files/drupal8-mariadb/.lagoon.yml
  tests/files/drupal8-mariadb/drush/aliases.drushrc.php
  tests/files/drupal8-postgres/.lagoon.yml
  tests/files/drupal8-postgres/drush/aliases.drushrc.php
  tests/files/drupal9-mariadb/.lagoon.yml
  tests/files/drupal9-mariadb/drush/aliases.drushrc.php
  tests/tasks/api/refresh-token.yaml
  tests/tasks/webhook-bitbucket/pullrequest-closed.yaml
  tests/tasks/webhook-bitbucket/pullrequest-opened.yaml
  tests/tasks/webhook-bitbucket/pullrequest-updated.yaml
  tests/tests/bitbucket.yaml
Labels: 6-images-testing

#2349 Split drupal tests by php version and reduce shared storage size in CI
  Makefile
  tests/files/drupal8-mariadb-single/docker-compose.yml
  tests/files/drupal8-mariadb/docker-compose.yml
  tests/files/drupal8-postgres/docker-compose.yml
  tests/files/drupal9-mariadb/docker-compose.yml
  tests/tests/drupal-php72.yaml
  tests/tests/drupal-php73.yaml
  tests/tests/drupal-php74.yaml
  tests/tests/drupal.yaml
Labels: 6-images-testing, Lagoon2.0

#2343 Harbor Robot Account Generation Fixup
  services/api/src/resources/project/harborSetup.ts
Labels: 2-build-deploy

#2339 Check for the existence of private container registry password better
  images/kubectl-build-deploy-dind/build-deploy.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy

#2307 Make the prebackuppod wait until the backup completes
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch-cluster/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-dbaas/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-shared/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mongo/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/postgres/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq-cluster/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/redis-persistent/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/solr/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/varnish-persistent/prebackuppod.yml
Labels: 8-automation-helpers

#2341 Correctly set the service type override variable and dbaas environment overrides
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy
