Repository uselagoon/lagoon, pull requests merged in 2020-01, with the labels that each got.

#1517 Pin Python Alpine to 3.10 instead of latest
  images/python/Dockerfile
Labels: 6-images-testing

#1522 Documentation Update Round 1!
  docs/administering_lagoon/install.md
  docs/developing_lagoon/api-debugging.md
  docs/developing_lagoon/contributing.md
  docs/developing_lagoon/index.md
  docs/using_lagoon/build_deploy_process.md
  docs/using_lagoon/configure_webhooks.md
  docs/using_lagoon/docker-compose_yml.md
  docs/using_lagoon/docker_images/nginx.md
  docs/using_lagoon/docker_images/php-cli.md
  docs/using_lagoon/docker_images/php-fpm.md
  docs/using_lagoon/drupal/drush9.md
  docs/using_lagoon/drupal/first_deployment.md
  docs/using_lagoon/drupal/lagoonize.md
  docs/using_lagoon/drupal/services/mariadb.md
  docs/using_lagoon/drupal/services/redis.md
  docs/using_lagoon/drupal/services/solr.md
  docs/using_lagoon/drupal/services/varnish.md
  docs/using_lagoon/environment_types.md
  docs/using_lagoon/environment_variables.md
  docs/using_lagoon/first_deployment.md
  docs/using_lagoon/golive.md
  docs/using_lagoon/graphql_api.md
  docs/using_lagoon/index.md
  docs/using_lagoon/lagoon_yml.md
  docs/using_lagoon/local_development_environments.md
  docs/using_lagoon/logging/kibana_examples.md
  docs/using_lagoon/logging/logging.md
  docs/using_lagoon/migrations/amazeeio.md
  docs/using_lagoon/service_types.md
  docs/using_lagoon/setup_project.md
  docs/using_lagoon/workflows.md
  mkdocs.yml
Labels: 7-documentation-examples

#1513 Remove unused variable
  helpers/run-in-all-lagoon-projects.sh
Labels: 8-automation-helpers

#1534 Configure Lagoon project for "release-drafter" Github Action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: 7-documentation-examples

#1535 Switch tests to use docker library alpine image
  tests/Dockerfile
  tests/ansible.cfg
Labels: 6-images-testing

#1516 Update tests dependencies to run only once in the right order
  Makefile
Labels: 6-images-testing

#1520 Fix some ansible warnings in test suite
  tests/checks/check-url-header-absent.yaml
  tests/checks/check-url-header.yaml
  tests/tasks/git-init.yaml
Labels: 6-images-testing

#1524 Remove unnecessary sleep in Jenkinsfile
  Jenkinsfile
Labels: 6-images-testing

#1525 Run the securityadmin demo script as part of make up
  Makefile
Labels: 6-images-testing

#1495 Harbor 1.10 upgrade
  .lagoon.harbor-secrets.yaml
  Makefile
  docker-compose.yaml
  lagoon-remote/docker-compose.yaml
  lagoon-remote/harbor-clair
  lagoon-remote/harborclair
  lagoon-remote/harborclairadapter
  services/harbor-clair/Dockerfile
  services/harbor-clair/docker-entrypoint.sh
  services/harbor-core/0015_1.10.0_schema.up.sql
  services/harbor-core/Dockerfile
  services/harbor-core/harbor-core.yml
  services/harbor-jobservice/Dockerfile
  services/harbor-jobservice/harbor-jobservice.yml
  services/harbor-nginx/Dockerfile
  services/harbor-nginx/harbor-nginx.yml
  services/harbor-nginx/nginx.conf
  services/harbor-portal/Dockerfile
  services/harbor-redis/Dockerfile
  services/harborclair/Dockerfile
  services/harborclair/docker-entrypoint.sh
  services/harborclair/harborclair.yml
  services/harborclair/install_cert.sh
  services/harborclairadapter/Dockerfile
  services/harborclairadapter/harborclair.yml
  services/harborregistry/Dockerfile
  services/harborregistry/entrypoint.sh
  services/harborregistry/harborregistry.yml
  services/harborregistry/install_cert.sh
  services/harborregistryctl/Dockerfile
  services/harborregistryctl/install_cert.sh
  services/harborregistryctl/start.sh
Labels: 2-build-deploy, harbor

#1503 Sync output of parallel make tasks in CI
  Jenkinsfile
Labels: 6-images-testing

#1554 Update New Relic PHP Agent to 9.6.0.255 and pin Xdebug to 2.6.0 for PHP 7.0
  images/php/fpm/Dockerfile
Labels: 6-images-testing

#1564 Document how Drupal can be run in a subfolder
  docs/using_lagoon/drupal/subfolders.md
  mkdocs.yml
Labels: 7-documentation-examples

#1586 add broker-single as a build dependency of broker
  Makefile
Labels: 0-kubernetes

#1607 initial K8s charts tidyup
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-shared/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/redis/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/values.yaml
Labels: 0-kubernetes, helmcharts

#1604 helm chart for mariadb-single
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/values.yaml
Labels: 0-kubernetes, helmcharts

#1608 adding logstash helm chart
  images/kubectl-build-deploy-dind/helmcharts/logstash/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/logstash/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/values.yaml
Labels: 0-kubernetes, helmcharts

#1606 #1598 - solr helmchart
  images/kubectl-build-deploy-dind/helmcharts/solr/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/solr/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/values.yaml
Labels: 0-kubernetes, helmcharts

#1576 All branches and pull requests that do not match the supplied regex to still be removed from OpenShift
  local-dev/api-data/01-populate-api-data.gql
  node-packages/commons/src/tasks.js
  services/webhooks2tasks/src/handlers/bitbucketBranchDeleted.js
  services/webhooks2tasks/src/handlers/githubBranchDeleted.js
  services/webhooks2tasks/src/handlers/gitlabBranchDeleted.js
  tests/tests/github.yaml
  tests/tests/github/branch-picky.yaml
Labels: 1-api-auth

#1532 Additional check for newrelic when container starts
  images/php/fpm/entrypoints/71-php-newrelic.sh
Labels: 2-build-deploy

#1512 Improvements to the auto-idler
  docker-compose.yaml
  services/auto-idler/Dockerfile
  services/auto-idler/idle-clis.sh
  services/auto-idler/idle-services.sh
  services/auto-idler/openshift-clis.sh
  services/auto-idler/openshift-services.sh
Labels: 8-automation-helpers

#1502 Silence useless "command not found" if minishift not installed
  Makefile
Labels: 6-images-testing

#1489 Fix regex to handle all possible IP addresses
  Makefile
Labels: 6-images-testing

#1461 Stub file timeout
  docs/using_lagoon/drupal/drupal7-mariadb/drush/aliases.drushrc.php
  docs/using_lagoon/drupal/drupal8-composer-mariadb/drush/aliases.drushrc.php
  docs/using_lagoon/drupal/drupal8-composer-postgres/drush/aliases.drushrc.php
  services/drush-alias/web/aliases.drushrc.php.stub
  tests/files/drupal8-mariadb/drush/aliases.drushrc.php
  tests/files/drupal8-postgres/drush/aliases.drushrc.php
Labels: 8-automation-helpers
