Repository uselagoon/lagoon, pull requests merged in 2020-03, with the labels that each got.

#1686 Kubernetes jobsmonitor Service
  Makefile
  docker-compose.yaml
  images/yarn-workspace-builder/Dockerfile
  openshift-setup/force-one-pod.yaml
  services/kubernetesjobs/LICENSE.md
  services/kubernetesjobsmonitor/.gitignore
  services/kubernetesjobsmonitor/Dockerfile
  services/kubernetesjobsmonitor/package.json
  services/kubernetesjobsmonitor/src/index.ts
  services/kubernetesjobsmonitor/tsconfig.json
Labels: 0-kubernetes

#1700 Shared cleanup script bug fix
  helpers/shared-cleanup.sh
Labels: 8-automation-helpers

#1691 Allow logs2logs-db to create missing lagoon-logs exchange
  services/logs2logs-db/pipeline/lagoon-logs.conf
Labels: 3-logging-reporting

#1721 Remove tty creation of ssh call inside drush aliases
  services/drush-alias/web/aliases.drushrc.php.stub
Labels: 1-api-auth

#1563 Harbor k8s
  Makefile
  docker-compose.yaml
  images/docker-host/Dockerfile
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/build-deploy.sh
  images/kubectl-build-deploy-dind/scripts/exec-push-parallel.sh
  images/kubectl/Dockerfile
  local-dev/k3d-registries.yaml
  services/api-db/docker-entrypoint-initdb.d/00-tables.sql
  services/api-db/docker-entrypoint-initdb.d/01-migrations.sql
  services/api/src/clients/harborClient.js
  services/api/src/resources/env-variables/resolvers.js
  services/api/src/resources/project/harborSetup.js
  services/api/src/resources/project/resolvers.js
  services/api/src/typeDefs.js
  services/harbor-core/ci-secret.key
  services/harbor-core/ci_tls.crt
  services/harbor-core/ci_tls.key
  services/harbor-core/harbor-core_ci.conf.yaml
  services/harbor-jobservice/ci-config.yaml
  services/harbor-nginx/ci.nginx.conf
  services/harborclair/ci-config.yaml
  services/harborregistry/install_cert.sh
  services/harborregistry/registry_ci.cfg.yaml
  services/harborregistryctl/registryctl_ci.cfg.yaml
Labels: 0-kubernetes

#1713 Add `drush uli` task to API and UI
  docs/administering_lagoon/rbac.md
  services/api/src/resolvers.js
  services/api/src/resources/task/resolvers.js
  services/api/src/typeDefs.js
  services/keycloak/start.sh
  services/ui/src/components/AddTask/components/DrushUserLogin.js
  services/ui/src/components/AddTask/components/DrushUserLogin.js.ignore
  services/ui/src/components/AddTask/index.js
  services/ui/src/components/AddTask/logic.js
Labels: 1-api-auth

#1724 Feature/2577 deployment success failure msg
  node-packages/commons/src/api.js
  services/api/src/resolvers.js
  services/api/src/resources/deployment/resolvers.js
  services/api/src/resources/project/helpers.js
  services/api/src/resources/project/sql.js
  services/api/src/typeDefs.js
  services/kubernetesbuilddeploymonitor/src/index.js
  services/openshiftbuilddeploymonitor/src/index.js
Labels: 0-kubernetes

#1694 K8s DBaaS Operator improvments
  charts/dbaas-operator.yaml
  charts/dbaas-providers.yaml
Labels: 0-kubernetes

#1654 Rename dbaas-shared to mariadb-dbaas
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/dbaas-shared/templates/crd.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/templates/dbaas.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/values.yaml
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-mariadb-dbaas.sh
Labels: 0-kubernetes

#1710 Fix incorrect variable name that caused errors with API subscriptions and fix error logging
  services/api/src/apolloServer.js
  services/ui/src/lib/ApiConnection.js
Labels: 1-api-auth

#1742 Update New Relic to v9.8.0.259
  images/php/fpm/Dockerfile
Labels: 6-images-testing

#1744 Updating composer to v1.10.1
  images/php/cli/Dockerfile
Labels: 6-images-testing

#1707 Prevent service broker environment variables having dashes.
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy

#1669 Fixes 1101 - Comments out scripts folder from dockerfile.
  docs/using_lagoon/drupal/drupal8-composer-mariadb/cli.dockerfile
  docs/using_lagoon/drupal/drupal8-composer-postgres/cli.dockerfile
Labels: 7-documentation-examples

#1547 #1449 move cronjobs into environment variable to force in-pod cronjob
  .lagoon.yml
  services/logs-db-curator/.lagoon.app.yml
Labels: 3-logging-reporting

#1745 Bug fix: Self-Service ssh key adds `_` if the ssh key has a comment
  services/api/src/resources/sshKey/resolvers.js
Labels: 1-api-auth, bug

#1740 Deleting environment variable permission issue - Hot Fix
  services/api/src/resources/env-variables/sql.js
Labels: 1-api-auth, bug

#1649 add kibana helm chart
  images/kubectl-build-deploy-dind/helmcharts/kibana/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/values.yaml
Labels: 0-kubernetes, helmcharts

#1716 Cater for missing extensions in the restic backups.
  services/webhooks2tasks/src/handlers/resticbackupSnapshotFinished.js
Labels: 3-logging-reporting

#1693 Don't require token authentication for local k3d dashboard
  Makefile
Labels: 0-kubernetes

#1683 K8s MariaDBConsumer check
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 0-kubernetes

#1737 Check for a mariadb-shared service instance in the namespace
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 8-automation-helpers

#1749 replace `auth can-i` with just `get`
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 0-kubernetes, 2-build-deploy

#1751 Add Restart Flags for Harbor Containers When Running Locally
  docker-compose.yaml
Labels: 2-build-deploy

#1680 Add Harbor Docs
  docs/using_lagoon/harbor/container_overview.png
  docs/using_lagoon/harbor/harbor-container-settings/harbor-core.md
  docs/using_lagoon/harbor/harbor-container-settings/harbor-database.md
  docs/using_lagoon/harbor/harbor-container-settings/harbor-jobservice.md
  docs/using_lagoon/harbor/harbor-container-settings/harborclair.md
  docs/using_lagoon/harbor/harbor-container-settings/harborclairadapter.md
  docs/using_lagoon/harbor/harbor-container-settings/harborregistry.md
  docs/using_lagoon/harbor/harbor-container-settings/harborregistryctl.md
  docs/using_lagoon/harbor/harbor_settings.md
  docs/using_lagoon/harbor/projects_overview.png
  docs/using_lagoon/harbor/repositories_overview.png
  docs/using_lagoon/harbor/scanning_image_1.png
  docs/using_lagoon/harbor/security_scanning.md
  docs/using_lagoon/harbor/using_harbor.md
  mkdocs.yml
Labels: 0-kubernetes, 2-build-deploy, 7-documentation-examples
