Repository uselagoon/lagoon, pull requests merged in 2020-05, with the labels that each got.

#1832 Limit k3d cluster name length
  Makefile
Labels: 6-images-testing

#1829 Support k3d running in docker on btrfs
  Makefile
Labels: 2-build-deploy

#1839 Fix typo in api subscription constructor
  services/api/src/apolloServer.js
Labels: 1-api-auth

#1841 handle empty hours in hits
  services/api/src/models/environment.ts
Labels: 8-automation-helpers

#1838 Update Newrelic 9.10.0.262 and install Newrelic on PHP 7.4
  images/php/fpm/Dockerfile
Labels: 6-images-testing

#1814 Upgrade ElasticSearch/Kibana to 7.6.1
  Makefile
  docs/using_lagoon/docker_images/elasticsearch.md
  docs/using_lagoon/index.md
  images/elasticsearch/Dockerfile6
  images/elasticsearch/Dockerfile7
  images/elasticsearch/Dockerfile7.1
  images/kibana/Dockerfile7
  images/kibana/Dockerfile7.1
  services/logs-db-ui/Dockerfile
  services/logs-db/Dockerfile
Labels: 3-logging-reporting, 6-images-testing

#1845 Add logs-dispatcher service image
  Makefile
  services/logs-dispatcher/Dockerfile
  services/logs-dispatcher/entrypoint.sh
  services/logs-dispatcher/fluent.conf
Labels: 3-logging-reporting, 6-images-testing

#1846 Use labels on kubernetes jobs to not block builds on cron/backups/tasks
  services/kubernetesbuilddeploy/src/index.js
  services/kubernetesdeployqueue/src/index.js
  services/kubernetesjobs/src/index.ts
  services/openshiftjobs/src/index.js
Labels: 2-build-deploy

#1849 Add (non-admin) users who create projects as owners of the created pr…
  services/api/src/resources/project/resolvers.js
Labels: 1-api-auth

#1847 Allow the lagoon UI to pre-select a keycloak identity provider for login
  services/ui/src/lib/util.js
  services/ui/src/lib/withKeycloak.js
  services/ui/src/pages/index.js
Labels: 1-api-auth

#1833 Label namespaces with lagoon/project in k8s
  Makefile
  services/kubernetesbuilddeploy/src/index.js
  tests/Dockerfile
  tests/checks/check-namespace-labels.yaml
  tests/tests/features-kubernetes.yaml
  tests/tests/features/namespace-labels.yaml
Labels: 2-build-deploy

#1810 Add Node.js v14 images
  Makefile
  tests/files/node14/.dockerignore
  tests/files/node14/.lagoon.yml
  tests/files/node14/Dockerfile
  tests/files/node14/docker-compose.yml
  tests/files/node14/index.js
  tests/files/node14/package.json
  tests/files/node14/yarn.lock
  tests/tests/node.yaml
Labels: 6-images-testing

#1809 Fix running cron via UI tasks
  services/ui/src/components/AddTask/components/DrushCron.js
Labels: 1-api-auth, ui

#1821 Add Github issue template config with a link to Discussions feature
  .github/ISSUE_TEMPLATE/config.yml
Labels: 7-documentation-examples

#1800 Adding the --compatability flag to all `docker-compose up -d` commands.
  Makefile
Labels: 2-build-deploy

#1792 Pricing Fix - Hotfix
  services/api/src/resources/billing/pricing.ts
Labels: 8-automation-helpers

#1794 Destructive Action Button Color
  services/ui/src/components/BillingModifiers/AllBillingModifiers.js
  services/ui/src/components/Button/index.js
  services/ui/src/components/DeleteConfirm/index.js
  services/ui/src/components/SshKeys/index.js
  services/ui/src/lib/variables.js
Labels: ui

#1790 Fix favicon URL typo
  services/ui/src/components/Favicon/index.js
Labels: 1-api-auth, ui

#1719 [Harbor] Custom S3 Region Endpoint Support
  services/harborregistry/Dockerfile
  services/harborregistry/entrypoint.sh
  services/harborregistry/harborregistry.yml
Labels: 2-build-deploy

#1770 Added support for ImageMagick in php images
  images/php/fpm/Dockerfile
Labels: 6-images-testing

#1796 Added documentation snippet for generating JWT on command line.
  docs/administering_lagoon/graphql_api.md
Labels: 7-documentation-examples

#1858 Added "Admin & UI subsystem" to release-drafter
  .github/release-drafter.yml
Labels: skip-changelog

#1862 only run helm template if the folder actually exists
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-resources-with-images.sh
Labels: 2-build-deploy

#1864 k8s k8up backup fixes
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
Labels: 8-automation-helpers

#1866 Update MariaDB image to latest Alpine & remove Galera-based images
  Makefile
  docs/using_lagoon/drupal/services/mariadb.md
  docs/using_lagoon/lagoon_yml.md
  docs/using_lagoon/service_types.md
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/mariadb-galera-drupal/Dockerfile
  images/mariadb-galera/Dockerfile
  images/mariadb-galera/entrypoints/100-fix-data-subpath.sh
  images/mariadb-galera/entrypoints/100-mariadb-logging.bash
  images/mariadb-galera/entrypoints/150-mariadb-performance.bash
  images/mariadb-galera/entrypoints/200-mariadb-envplate.bash
  images/mariadb-galera/entrypoints/201-maxscale-envplate.bash
  images/mariadb-galera/entrypoints/9999-mariadb-galera-init.bash
  images/mariadb-galera/maxscale-start.sh
  images/mariadb-galera/maxscale.cnf
  images/mariadb-galera/maxscale.sql
  images/mariadb-galera/my.cnf
  images/mariadb-galera/mysql-backup.sh
  images/mariadb-galera/root/usr/bin/peer-finder
  images/mariadb-galera/root/usr/include/bits/wordsize.h
  images/mariadb-galera/root/usr/share/container-scripts/mysql/configure-galera.sh
  images/mariadb-galera/root/usr/share/container-scripts/mysql/galera.cnf
  images/mariadb-galera/root/usr/share/container-scripts/mysql/readiness-probe.sh
  images/mariadb/Dockerfile
  images/mariadb/entrypoints/9999-mariadb-init.bash
  images/mariadb/my.cnf
  images/mariadb/root/usr/share/container-scripts/mysql/readiness-probe.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/mariadb-galera/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-galera/services.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-galera/statefulset.yml
  local-dev/api-data/02-populate-api-data-openshift.gql
  local-dev/api-data/03-populate-api-data-kubernetes.gql
  local-dev/git/Dockerfile
  services/api-db/Dockerfile-galera
  services/keycloak-db/Dockerfile-galera
  tests/files/drupal8-dockerfiles/php7.2-galera/builder.dockerfile
  tests/files/drupal8-dockerfiles/php7.2-galera/mariadb.dockerfile
  tests/files/drupal8-dockerfiles/php7.2-galera/nginx.dockerfile
  tests/files/drupal8-dockerfiles/php7.2-galera/php.dockerfile
  tests/files/drupal8-dockerfiles/php7.2-galera/redis.dockerfile
  tests/files/drupal8-dockerfiles/php7.2-galera/solr.dockerfile
  tests/files/drupal8-dockerfiles/php7.2-galera/varnish.dockerfile
  tests/tests/drupal-galera.yaml
Labels: 6-images-testing

#1865 Disabling quota sync for harbor-core
  services/harbor-core/harbor-core.yml
Labels: 2-build-deploy

#1881 Hide active/standby visibility on projects that can't use it
  services/ui/src/components/ActiveStandbyConfirm/index.js
  services/ui/src/components/Environment/index.js
  services/ui/src/components/Environments/index.js
  services/ui/src/components/ProjectDetailsSidebar/index.js
  services/ui/src/lib/query/ProjectByName.js
Labels: skip-changelog

#1891 Run mysql_upgrade on existing databases after upgrade
  images/mariadb/Dockerfile
  images/mariadb/entrypoints/9999-mariadb-init.bash
Labels: 6-images-testing

#1859 Lagoon logging helm chart
  charts/index.yaml
  charts/lagoon-logging-0.1.0.tgz
  charts/lagoon-logging.values.yaml
  charts/lagoon-logging/.gitignore
  charts/lagoon-logging/.helmignore
  charts/lagoon-logging/Chart.lock
  charts/lagoon-logging/Chart.yaml
  charts/lagoon-logging/README.md
  charts/lagoon-logging/templates/NOTES.txt
  charts/lagoon-logging/templates/_helpers.tpl
  charts/lagoon-logging/templates/clusterflow.yaml
  charts/lagoon-logging/templates/clusteroutput.yaml
  charts/lagoon-logging/templates/logging.yaml
  charts/lagoon-logging/templates/logs-dispatcher.clusterrolebinding.yaml
  charts/lagoon-logging/templates/logs-dispatcher.env.configmap.yaml
  charts/lagoon-logging/templates/logs-dispatcher.fluent-conf.configmap.yaml
  charts/lagoon-logging/templates/logs-dispatcher.secret.yaml
  charts/lagoon-logging/templates/logs-dispatcher.service.yaml
  charts/lagoon-logging/templates/logs-dispatcher.serviceaccount.yaml
  charts/lagoon-logging/templates/logs-dispatcher.statefulset.yaml
  charts/lagoon-logging/templates/tests/test-connection.yaml
  charts/lagoon-logging/values.yaml
Labels: 3-logging-reporting

#1917 Ensure project and environment labels exist on OpenShift projects.
  services/openshiftbuilddeploy/src/index.js
Labels: 2-build-deploy

#1914 Automated Billing - Poly Site Calculations
  services/api/src/helpers/billingGroups.ts
  services/api/src/models/group.ts
  services/api/src/resources/billing/billingCalculations.test.ts
  services/api/src/resources/billing/billingCalculations.ts
  services/api/src/resources/billing/helpers.ts
  services/api/src/resources/billing/pricing.ts
  services/api/src/typeDefs.js
  services/ui/src/components/BillingGroup/index.js
Labels: 8-automation-helpers

#1906 Reformat and update Lagoon service README files
  services/auth-server/README.md
  services/kubernetesbuilddeploy/README.md
Labels: 7-documentation-examples

#1903 Ingress annotations
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/custom-ingress/templates/ingress.yaml
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-resources-with-images.sh
  images/kubectl-build-deploy-dind/scripts/exec-kubernetes-resources.sh
Labels: 2-build-deploy

#1830 Re-implement JWT generation script using pyjwt
  local-dev/api-data-watcher-pusher/Dockerfile
  local-dev/api-data-watcher-pusher/api-watch-push.sh
  local-dev/api-data-watcher-pusher/create_jwt.py
  local-dev/api-data-watcher-pusher/create_jwt.sh
  services/auto-idler/Dockerfile
  services/auto-idler/create_jwt.py
  services/auto-idler/create_jwt.sh
  services/auto-idler/idle-clis.sh
  services/auto-idler/idle-services.sh
  services/ssh/Dockerfile
  services/ssh/authorize.sh
  services/ssh/create_60_sec_jwt.py
  services/ssh/create_60_sec_jwt.sh
  services/storage-calculator/Dockerfile
  services/storage-calculator/calculate-storage.sh
  services/storage-calculator/create_jwt.py
  services/storage-calculator/create_jwt.sh
Labels: 1-api-auth, 9-security

#1803 Fix markdown rendering for code blocks for container registries
  docs/using_lagoon/lagoon_yml.md
Labels: 7-documentation-examples

#1698 Basic Authentication documentation update
  docs/using_lagoon/docker_images/nginx.md
  images/nginx/docker-entrypoint
Labels: 7-documentation-examples

#1886 Moved es-curl to elasticsearch base images
  images/elasticsearch/Dockerfile6
  images/elasticsearch/Dockerfile7
  images/elasticsearch/es-curl
  services/logs-db/Dockerfile
  services/logs-db/es-curl
Labels: 6-images-testing

#1912 Add Trivy Scanner to Harbor
  Makefile
  docker-compose.yaml
  services/harbor-core/Dockerfile
  services/harbor-core/harbor-core.yml
  services/harbor-jobservice/Dockerfile
  services/harbor-trivy/Dockerfile
  services/harbor-trivy/entrypoint.sh
  services/harbor-trivy/harbor-trivy.yml
  services/harbor-trivy/install_cert.sh
  services/harborclair/Dockerfile
  services/harborclair/ci-config.yaml
  services/harborclair/docker-entrypoint.sh
  services/harborclair/harborclair.yml
  services/harborclairadapter/Dockerfile
  services/harborclairadapter/harborclair.yml
Labels: 2-build-deploy

#1889 Build Python3.7 images from Alpine 3.10 instead of 3.11
  Makefile
Labels: 6-images-testing

#1874 Elasticsearch date bounds calculate
  services/api/src/models/environment.ts
Labels: 10-admin-user-interfaces

#1904 Initial attempt at d9 tests
  tests/files/drupal9-dockerfiles/php7.4/builder.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/mariadb.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/nginx.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/php.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/postgres.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/redis.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/solr.dockerfile
  tests/files/drupal9-dockerfiles/php7.4/varnish.dockerfile
  tests/files/drupal9-mariadb/.dockerignore
  tests/files/drupal9-mariadb/.gitignore
  tests/files/drupal9-mariadb/.lagoon.yml
  tests/files/drupal9-mariadb/LICENSE
  tests/files/drupal9-mariadb/README.md
  tests/files/drupal9-mariadb/composer.json
  tests/files/drupal9-mariadb/composer.lock
  tests/files/drupal9-mariadb/config/sync/.gitkeep
  tests/files/drupal9-mariadb/config/sync/.htaccess
  tests/files/drupal9-mariadb/docker-compose.yml
  tests/files/drupal9-mariadb/drupal.sql.gz
  tests/files/drupal9-mariadb/drush/README.md
  tests/files/drupal9-mariadb/drush/aliases.drushrc.php
  tests/files/drupal9-mariadb/drush/drush.yml
  tests/files/drupal9-mariadb/drush/drushrc.php
  tests/files/drupal9-mariadb/drush/policy.drush.inc
  tests/files/drupal9-mariadb/scripts/composer/ScriptHandler.php
  tests/files/drupal9-mariadb/web/.csslintrc
  tests/files/drupal9-mariadb/web/.editorconfig
  tests/files/drupal9-mariadb/web/.eslintignore
  tests/files/drupal9-mariadb/web/.eslintrc.json
  tests/files/drupal9-mariadb/web/.gitattributes
  tests/files/drupal9-mariadb/web/.ht.router.php
  tests/files/drupal9-mariadb/web/.htaccess
  tests/files/drupal9-mariadb/web/autoload.php
  tests/files/drupal9-mariadb/web/index.php
  tests/files/drupal9-mariadb/web/modules/.gitkeep
  tests/files/drupal9-mariadb/web/profiles/.gitkeep
  tests/files/drupal9-mariadb/web/robots.txt
  tests/files/drupal9-mariadb/web/sites/default/all.services.yml
  tests/files/drupal9-mariadb/web/sites/default/all.settings.php
  tests/files/drupal9-mariadb/web/sites/default/default.services.yml
  tests/files/drupal9-mariadb/web/sites/default/default.settings.php
  tests/files/drupal9-mariadb/web/sites/default/development.services.yml
  tests/files/drupal9-mariadb/web/sites/default/development.settings.php
  tests/files/drupal9-mariadb/web/sites/default/example.settings.local.php
  tests/files/drupal9-mariadb/web/sites/default/production.services.yml
  tests/files/drupal9-mariadb/web/sites/default/production.settings.php
  tests/files/drupal9-mariadb/web/sites/default/settings.php
  tests/files/drupal9-mariadb/web/sites/example.sites.php
  tests/files/drupal9-mariadb/web/themes/.gitkeep
  tests/files/drupal9-mariadb/web/update.php
  tests/files/drupal9-mariadb/web/web.config
  tests/tests/drupal.yaml
Labels: 6-images-testing

#1835 use `lagoon.sh` as label prefix
  charts/lagoon-remote/values.yaml
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/custom-ingress/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/custom-ingress/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/mariadb-dbaas/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/node/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/ingress.yaml
  images/kubectl-build-deploy-dind/scripts/exec-pre-tasks-run.sh
  images/kubectl-build-deploy-dind/scripts/exec-tasks-run.sh
  services/ssh/home/rsh.sh
Labels: 2-build-deploy

#1921 Ability to temporarily disable pre or post rollout tasks
  docs/using_lagoon/lagoon_yml.md
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
Labels: 2-build-deploy

#1870 Alter the error message for webhook payloads that are not JSON.
  services/webhook-handler/src/extractWebhookData.js
Labels: 8-automation-helpers

#1923 Redeploy pods if the ConfigMap changes
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/values.yaml
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/cli-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/cli/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch-cluster/statefulset.yml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/kibana/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/logstash/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/mariadb-single/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/mongo/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/nginx-php-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/nginx-php-redis-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/nginx-php/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/nginx/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/node-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/node/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/postgres/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/python-ckandatapusher/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq-cluster/statefulset.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/redis-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/redis/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/solr/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/varnish-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/varnish/deployment.yml
  images/oc-build-deploy-dind/scripts/exec-openshift-resources-with-images.sh
Labels: 2-build-deploy
