Repository uselagoon/lagoon, pull requests merged in 2020-08, with the labels that each got.

#2132 Improve reliability of CI testing
  Makefile
Labels: 6-images-testing

#2031 Add readinessProbe to CLI containers
  images/commons/Dockerfile
  images/commons/entrypoint-readiness
  images/commons/lagoon/entrypoints/999-readiness.sh
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/deployment.yaml
  images/oc-build-deploy-dind/openshift-templates/cli-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/cli/deployment.yml
  images/php/cli/Dockerfile
Labels: 2-build-deploy

#2115 Updates healthz-php to version 0.0.6
  images/php/fpm/Dockerfile
Labels: 6-images-testing

#2120 Add `api-redis` to `make api/ui-development`
  Makefile
Labels: 8-automation-helpers

#2136 Reduce Parallelism and Document Testing Steps
  Jenkinsfile
Labels: 6-images-testing

#2152 Add `skip-openshift-tests` label to Jenkins to reduce intermittent test failures
  Jenkinsfile
Labels: 6-images-testing
