Repository uselagoon/lagoon, pull requests merged in 2020-04, with the labels that each got.

#1704 Active/Standby Implementation
  Makefile
  docs/developing_lagoon/index.md
  docs/using_lagoon/active_standby.md
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/configmap.yml
  images/oc-build-deploy-dind/openshift-templates/route.yml
  images/oc-build-deploy-dind/scripts/exec-openshift-create-route.sh
  local-dev/api-data/02-populate-api-data-openshift.gql
  local-dev/git/Dockerfile
  node-packages/commons/src/api.js
  node-packages/commons/src/openshiftApi.js
  node-packages/commons/src/tasks.js
  openshift-setup/dioscuri-operator.yaml
  openshift-setup/dioscuri-roles.yaml
  services/api-db/docker-entrypoint-initdb.d/00-tables.sql
  services/api-db/docker-entrypoint-initdb.d/01-migrations.sql
  services/api-db/docker-entrypoint-initdb.d/03-procedures.sql
  services/api/src/mocks.js
  services/api/src/models/project.ts
  services/api/src/resolvers.js
  services/api/src/resources/deployment/resolvers.js
  services/api/src/resources/project/resolvers.js
  services/api/src/typeDefs.js
  services/drush-alias/web/aliases.drushrc.php.stub
  services/openshiftbuilddeploy/src/index.js
  services/openshiftbuilddeploymonitor/src/index.js
  services/openshiftmisc/Dockerfile
  services/openshiftmisc/src/handlers/routeMigration.js
  services/openshiftmisc/src/index.js
  services/ui/src/components/ActiveStandbyConfirm/index.js
  services/ui/src/components/ActiveStandbyConfirm/index.stories.js
  services/ui/src/components/Environment/index.js
  services/ui/src/components/Environments/index.js
  services/ui/src/components/ProjectDetailsSidebar/index.js
  services/ui/src/lib/mutation/SwitchActiveStandby.js
  services/ui/src/lib/query/EnvironmentByOpenshiftProjectName.js
  services/ui/src/lib/query/ProjectByName.js
  tests/files/active-standby/first/.lagoon.env.nginx
  tests/files/active-standby/first/.lagoon.yml
  tests/files/active-standby/first/Dockerfile
  tests/files/active-standby/first/app/index.html
  tests/files/active-standby/first/docker-compose.yml
  tests/files/active-standby/first/redirects-map.conf
  tests/files/active-standby/second/.lagoon.env.nginx
  tests/files/active-standby/second/.lagoon.yml
  tests/files/active-standby/second/Dockerfile
  tests/files/active-standby/second/app/index.html
  tests/files/active-standby/second/docker-compose.yml
  tests/files/active-standby/second/redirects-map.conf
  tests/tests/active-standby.yaml
  tests/tests/active-standby/active-standby.yaml
  tests/tests/active-standby/deploy-active-standby.yaml
  tests/tests/active-standby/deploy-no-sha.yaml
  tests/tests/active-standby/git-add-commit-push.yaml
  tests/tests/active-standby/post-switch-check.yaml
  tests/tests/active-standby/pre-switch-check.yaml
  tests/tests/active-standby/remove.yaml
Labels: 1-api-auth, 2-build-deploy, 5-operators-provision, 6-images-testing

#1671 Variables from API escaped incorrectly in build-args
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/build-deploy.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  local-dev/api-data/02-populate-api-data-openshift.gql
  local-dev/api-data/03-populate-api-data-kubernetes.gql
  tests/files/features/Dockerfile
  tests/tests/features/lagoon-api-variables.yaml
Labels: 2-build-deploy

#1767 Harbor documentation bugfix
  mkdocs.yml
Labels: 7-documentation-examples

#1753 Add webhooks for all harbor projects when created
  services/api/src/resources/project/harborSetup.js
Labels: 2-build-deploy, 9-security

#1738 Fix issue with elasticsearch buffers overflowing in logs-forwarder
  services/logs-forwarder/.lagoon.multi.yml
  services/logs-forwarder/.lagoon.single.yml
Labels: 3-logging-reporting

#1780 Minor Makefile fixes
  Makefile
Labels: 2-build-deploy

#1781 Throttling Clair container
  Makefile
  docker-compose.yaml
Labels: 2-build-deploy

#1783 add `-o ConnectTimeout=5` to solve issues with Catalina 10.15.4 and proxy settings
  services/drush-alias/web/aliases.drushrc.php.stub
Labels: 8-automation-helpers

#1766 Update newrelic to v9.9.0.260
  images/php/fpm/Dockerfile
Labels: 6-images-testing

#1819 Fix for issue #1818. Pin ubuntu image version as 18.04 in ssh/Dockerfile
  services/ssh/Dockerfile
Labels: 6-images-testing

#1806 Add Harbor Migration Script
  services/api/package.json
  services/api/src/migrations/2-harbor/harborSync.ts
  services/api/src/resources/project/harborSetup.js
Labels: 2-build-deploy

#1526 Add workaround for missing localhost dns on linux
  Makefile
  docker-compose.yaml
Labels: 6-images-testing
