Repository uselagoon/lagoon, pull requests merged in 2021-04, with the labels that each got.

#2590 Document project default users and SSH keys
  docs/SUMMARY.md
  docs/using-lagoon-advanced/project-default-users-keys.md
Labels: 7-documentation-examples

#2329 Fix PHP 7.4 deprecated argument order for implode()
  docs/docs/examples/drupal7-mariadb/sites/default/settings.php
  tests/files/drupal8-mariadb-single/web/sites/default/settings.php
  tests/files/drupal8-mariadb/web/sites/default/settings.php
  tests/files/drupal8-postgres/web/sites/default/settings.php
  tests/files/drupal9-mariadb/web/sites/default/settings.php
Labels: 6-images-testing, 7-documentation-examples

#2604 revert fsGroup:0 for solr template
  images/kubectl-build-deploy-dind/helmcharts/solr/values.yaml
Labels: 0-kubernetes

#2605 Improved backupcommands for solr, postgres-single, and mongodb-single
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
Labels: 8-automation-helpers, skip-openshift-tests
