Repository uselagoon/lagoon, pull requests merged in 2021-03, with the labels that each got.

#2552 Bump kubectl version used in tests
  tests/Dockerfile
Labels: 6-images-testing

#2563 Add missing helm repos for CI
  Makefile
Labels: 6-images-testing

#2575 Use consistent quoting for file-based backup annotations
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
Labels: 0-kubernetes, skip-openshift-tests

#2557 Add option to mount local directories into lagoon-core pods for local development
  Makefile
  local-dev/kubectl-patches/api.yaml
  local-dev/kubectl-patches/auth-server.yaml
  local-dev/kubectl-patches/controllerhandler.yaml
  local-dev/kubectl-patches/logs2email.yaml
  local-dev/kubectl-patches/logs2microsoftteams.yaml
  local-dev/kubectl-patches/logs2rocketchat.yaml
  local-dev/kubectl-patches/logs2slack.yaml
  local-dev/kubectl-patches/ui.yaml
  local-dev/kubectl-patches/webhook-handler.yaml
  local-dev/kubectl-patches/webhooks2tasks.yaml
Labels: 0-kubernetes

#2567 Increment the correct variable in mongo dbaas deployment
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-mongodb-dbaas.sh
Labels: 2-build-deploy

#2582 trim routes that are longer than 53 for usage in helm release name
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/custom-ingress/templates/_helpers.tpl
Labels: skip-openshift-tests

#2566 Update remaining templates to use securityContext value
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
Labels: 2-build-deploy

#2565 Add Environment and Project IDs to controller builds
  node-packages/commons/src/api.ts
  node-packages/commons/src/tasks.ts
  services/controllerhandler/src/index.ts
Labels: 2-build-deploy, 5-operators-provision

#2583 Scale idled environments up if SSH connections are made
  services/ssh/home/rsh.sh
Labels: 2-build-deploy

#2589 set vm.max_map_count in elasticsearch template
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/deployment.yaml
Labels: 0-kubernetes, skip-openshift-tests
