Repository uselagoon/lagoon, pull requests merged in 2021-09, with the labels that each got.

#2821 Upgrade fluentd and enforce Opensearch compatibility in logs-concentrator
  services/logs-concentrator/Dockerfile
Labels: 3-logging-reporting

#2820 Custom Backup and Restore Location Support
  docs/using-lagoon-advanced/backups.md
  docs/using-lagoon-advanced/environment-variables.md
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/templates/custom-baas-backup-location-secret.yaml
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/templates/custom-baas-restore-location-secret.yaml
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/templates/schedule.yaml
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/values.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/templates/prebackuppod.yaml
  node-packages/commons/src/tasks.ts
  services/api/src/resources/backup/resolvers.ts
Labels: 1-api-auth, 2-build-deploy

#2843 Add a message for truncated results in the UI and allow users to select displayed number
  services/ui/src/components/ResultsLimited/index.js
  services/ui/src/components/ResultsLimited/index.stories.js
  services/ui/src/next.config.js
  services/ui/src/pages/backups.js
  services/ui/src/pages/deployments.js
  services/ui/src/pages/tasks.js
Labels: 10-admin-user-interfaces
