Repository uselagoon/lagoon, pull requests merged in 2021-02, with the labels that each got.

#2480 Bump CI tool versions: kind, helm, kubectl
  Makefile
Labels: 0-kubernetes

#2416 Add Mongodb DBAAS operator (PR2403 & PR2411)
  Makefile
  docker-compose.yaml
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/mongodb-dbaas/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/mongodb-dbaas/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/mongodb-dbaas/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/mongodb-dbaas/templates/dbaas.yaml
  images/kubectl-build-deploy-dind/helmcharts/mongodb-dbaas/values.yaml
  images/kubectl-build-deploy-dind/scripts/exec-kubectl-mongodb-dbaas.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/openshift-templates/mongodb-dbaas/consumer.yml
  images/oc-build-deploy-dind/scripts/exec-openshift-mongodb-dbaas.sh
  local-dev/api-data-watcher-pusher/api-data/02-populate-api-data-openshift.gql
  local-dev/api-data-watcher-pusher/api-data/03-populate-api-data-kubernetes.gql
  local-dev/git/Dockerfile
  local-dev/helm-values-mongodbprovider.yml
  local-dev/mongodb-dbaas-provider/Dockerfile
  local-dev/mongodb-dbaas-provider/mongo-init.js
  local-dev/mongodb-dbaas-provider/openssl-test-ca.cnf
  local-dev/mongodb-dbaas-provider/openssl-test-server.cnf
  openshift-setup/dbaas-operator.yaml
  openshift-setup/dbaas-providers.yaml
  openshift-setup/dbaas-roles.yaml
  tests/files/node-mongodb/.dockerignore
  tests/files/node-mongodb/.lagoon.yml
  tests/files/node-mongodb/Dockerfile
  tests/files/node-mongodb/Dockerfile.mongo
  tests/files/node-mongodb/controllers/list.js
  tests/files/node-mongodb/db.js
  tests/files/node-mongodb/docker-compose.yml
  tests/files/node-mongodb/index.js
  tests/files/node-mongodb/models/list.js
  tests/files/node-mongodb/mongodb/mongo-init.js
  tests/files/node-mongodb/mongodb/openssl-test-ca.cnf
  tests/files/node-mongodb/mongodb/openssl-test-server.cnf
  tests/files/node-mongodb/package.json
  tests/files/node-mongodb/routes/index.js
  tests/files/node-mongodb/routes/list.js
  tests/files/node-mongodb/views/getlist.html
  tests/files/node-mongodb/views/index.html
  tests/files/node-mongodb/views/list.html
  tests/tests/node-mongodb.yaml
  tests/tests/node-mongodb/check-deployed.yaml
  tests/tests/node-mongodb/node-mongodb.yaml
Labels: Lagoon2.0

#2510 Add elasticsearch-single helmchart to k8s (Lagoon-master)
  Makefile
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/values.yaml
  tests/files/elasticsearch/elasticsearch.dockerfile
  tests/tests/elasticsearch.yaml
Labels: 2-build-deploy, skip-openshift-tests

#2495 Minor controller fixes
  services/controllerhandler/src/index.ts
Labels: skip-openshift-tests

#2487 Don't create the MAIN_GENERATED_ROUTE if autogenerated routes are disabled
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
Labels: skip-openshift-tests

#2492 Remove prebackuppod definitions from all non clustered services
  docs/using_lagoon/backups.md
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/prebackuppod.yaml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/elasticsearch/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/mongo/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/mongo/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/postgres/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/postgres/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/rabbitmq/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/redis-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/redis-persistent/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/solr/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/solr/prebackuppod.yml
  images/oc-build-deploy-dind/openshift-templates/varnish-persistent/deployment.yml
  images/oc-build-deploy-dind/openshift-templates/varnish-persistent/prebackuppod.yml
Labels: 8-automation-helpers

#2509 Update Lagoon to Alpine 3.12 as per base images
  Makefile
  images/docker-host/Dockerfile
  images/kubectl/Dockerfile
  images/oc/Dockerfile
  images/rabbitmq/Dockerfile
  local-dev/api-data-watcher-pusher/Dockerfile
  local-dev/git/Dockerfile
  services/logs-tee/Dockerfile
Labels: 6-images-testing

#2515 Set StorageClass properly for node-persistent pvc
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/pvc.yaml
Labels: skip-openshift-tests

#2519 remove unused variable lagoonEnvironmentType
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
Labels: skip-openshift-tests

#2520 Add official fluentd output plugin for Datadog to logs-dispatcher
  services/logs-dispatcher/Dockerfile
Labels: 3-logging-reporting

#2506 DBaaS prebackup pod addition
  images/kubectl-build-deploy-dind/helmcharts/mongodb-dbaas/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-dbaas/templates/prebackuppod.yaml
Labels: 8-automation-helpers

#2493 Run in-pod cronjobs in /app
  tests/files/features/.lagoon.yml
  tests/tests/features/cronjobs.yaml
Labels: bug

#2524 Update build-deploy controller to latest version and fix pull request tests
  Jenkinsfile
  Makefile
  openshift-setup/lagoon-builddeploy-controller.yml
  openshift-setup/lagoon-builddeploy-crd.yml
  tests/tasks/api/pullrequest-deploy.yaml
  tests/tasks/webhook-bitbucket/pullrequest-closed.yaml
  tests/tasks/webhook-bitbucket/pullrequest-opened.yaml
  tests/tasks/webhook-bitbucket/pullrequest-updated.yaml
  tests/tasks/webhook-github/pullrequest-closed.yaml
  tests/tasks/webhook-github/pullrequest-opened.yaml
  tests/tasks/webhook-github/pullrequest-synchronize.yaml
  tests/tasks/webhook-gitlab/pullrequest-closed.yaml
  tests/tasks/webhook-gitlab/pullrequest-opened.yaml
  tests/tasks/webhook-gitlab/pullrequest-updated.yaml
  tests/tests/api/deploy-pullrequest.yaml
  tests/tests/bitbucket/pullrequest.yaml
  tests/tests/github/pullrequest.yaml
  tests/tests/gitlab/pullrequest.yaml
  tests/tests/python/deploy-pullrequest.yaml
  tests/tests/python/push.yaml
Labels: skip-kubernetes-tests

#2522 Limit the size of the CN field in certificate requests (backport)
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/node/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/python/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/ingress.yaml
  node-packages/commons/src/tasks.ts
  tests/checks/check-auto-generated-ingress-short-router-url.yaml
  tests/tests/features-kubernetes.yaml
  tests/tests/features/short-router-url.yaml
Labels: skip-openshift-tests

#2534 Bump kubectl and helm versions in the Lagoon kubectl base image
  images/kubectl/Dockerfile
Labels: 6-images-testing

#2517 Backporting private docker registry fixes from #2516 to master branch
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/build-deploy.sh
Labels: 2-build-deploy, skip-openshift-tests

#2531 Unconditionally refresh api token in test suite
  tests/tasks/api/refresh_token.py
Labels: 6-images-testing

#2512 Add official fluentd output plugin for Datadog to logs-dispatcher
  services/logs-dispatcher/Dockerfile
Labels: 3-logging-reporting

#2504 Limit the size of the CN field in certificate requests
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/node/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/python/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/ingress.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/ingress.yaml
  node-packages/commons/src/tasks.ts
  tests/checks/check-auto-generated-ingress-short-router-url.yaml
  tests/tests/features-kubernetes.yaml
  tests/tests/features/short-router-url.yaml
Labels: 0-kubernetes

#2503 initial ES helmchart (Lagoon 2.x)
  Makefile
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/prebackuppod.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/values.yaml
  tests/files/elasticsearch/elasticsearch.dockerfile
  tests/tests/elasticsearch.yaml
Labels: 2-build-deploy

#2516 Updating private registry support to handle private dockerhub images
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/build-deploy.sh
Labels: 2-build-deploy

#2539 fix bash spacing in retention checks
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/oc-build-deploy-dind/build-deploy-docker-compose.sh
  services/storage-calculator/calculate-storage.sh
Labels: 2-build-deploy, skip-kubernetes-tests

#2538 Matching kubectlbuilddeploy to tested version in #2516
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/build-deploy.sh
Labels: 2-build-deploy, skip-openshift-tests

#2540 Update fluentd to v1.12 in logs-dispatcher
  services/logs-dispatcher/Dockerfile
Labels: skip-openshift-tests

#2490 UI feature: Additional filters added to problems tab
  services/api/src/resources/problem/sql.ts
  services/ui/src/components/Dates/index.js
  services/ui/src/components/Problem/ContentDisplay/DrutinyContent.js
  services/ui/src/components/Problem/index.js
  services/ui/src/components/Problems/index.js
Labels: enhancement

#2479 Bump base image of logs-dispatcher
  services/logs-dispatcher/Dockerfile
Labels: 3-logging-reporting
