Repository uselagoon/lagoon, pull requests merged in 2021-05, with the labels that each got.

#2592 Updating backupcommands for solr, postgres-single, and mongodb-single
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
Labels: 8-automation-helpers

#2623 Backporting k8up backupcommand fixes from #2592
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/deployment.yaml
Labels: 5-operators-provision

#2642 Rabbitmq helmchart for master
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/.helmignore
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/Chart.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/_helpers.tpl
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/pvc.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/service.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/values.yaml
Labels: 2-build-deploy

#2648 Harbor 1.x Registry HA Support
  services/harborregistry/harborregistry.yml
Labels: 2-build-deploy

#2665 Allow Drush Cron task for Drupal 9
  services/api/src/resources/task/resolvers.ts
Labels: 8-automation-helpers

#2682 Fix active-standby development environment limit check
  node-packages/commons/src/api.ts
Labels: 2-build-deploy

#2681 Allow skipping Trivy scanning when building Lagoon
  Makefile
Labels: 2-build-deploy

#2643 Local dev DX improvements and bugfixes
  Makefile
  local-dev/api-data-watcher-pusher/api-data/01-populate-api-data-general.gql
Labels: 6-images-testing

#2683 Fix active-standby development environment limit check (lagoon 1)
  node-packages/commons/src/api.ts
Labels: 2-build-deploy, lagoon-one

#2676 Custom ingress template format fix
  images/kubectl-build-deploy-dind/helmcharts/custom-ingress/templates/ingress.yaml
Labels: lagoon-one, skip-openshift-tests
