Repository uselagoon/lagoon, pull requests merged in 2021-12, with the labels that each got.

#2831 Adding startingDeadlineSeconds to all cli native cronjob templates
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/cronjob.yaml
Labels: 2-build-deploy, 0-kubernetes

#2947 Refactor Storage Calculator to be more robust
  services/storage-calculator/README.md
  services/storage-calculator/calculate-storage.sh
Labels: 3-logging-reporting

#2967 prune dangling images on docker-host automatically
  images/docker-host/prune-images.sh
Labels: 8-automation-helpers

#2976 Update docs about `monitoring-path`
  docs/using-lagoon-the-basics/lagoon-yml.md
Labels: 7-documentation-examples
