Repository uselagoon/lagoon, pull requests merged in 2021-07, with the labels that each got.

#2735 Update developing Lagoon docs
  docs/contributing-to-lagoon/developing-lagoon.md
Labels: skip-kubernetes-tests

#2747 #2746 fix broken file upload with a workaround:
  services/api/src/resources/file/resolvers.ts
Labels: 1-api-auth

#2742 use S3_FILES_HOST instead of S3_HOST
  services/api/src/clients/aws.ts
Labels: 10-admin-user-interfaces

#2739 allow OPENSHIFT_REGEX to filter which openshifts are idled
  services/auto-idler/Dockerfile
  services/auto-idler/idle-clis.sh
  services/auto-idler/idle-services.sh
Labels: 8-automation-helpers

#2750 load esClient fresh insreat from the clients pool
  services/api/src/models/environment.ts
Labels: 1-api-auth

#2721 Custom Backup Schedules and Hourly Backup Retention Support
  docs/using-lagoon-the-basics/lagoon-yml.md
  images/kubectl-build-deploy-dind/build-deploy-docker-compose.sh
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/templates/schedule.yaml
  images/kubectl-build-deploy-dind/helmcharts/k8up-schedule/values.yaml
Labels: 8-automation-helpers, lagoon.yml

#2745 Updating k8up template backupcommand and file-extension annotations
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/deployment.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/deployment.yaml
  images/oc-build-deploy-dind/openshift-templates/mariadb-single/deployment.yml
Labels: 2-build-deploy

#2756 Updating Lagoon Backup docs
  docs/using-lagoon-advanced/backups.md
Labels: 7-documentation-examples, skip-kubernetes-tests

#2760 Set bulk SC for node-persistent pvc in OC template
  images/oc-build-deploy-dind/openshift-templates/node-persistent/pvc.yml
Labels: skip-kubernetes-tests

#2769 Update link to amazee.io Kibana in docs
  docs/logging/logging.md
Labels: 7-documentation-examples, skip-kubernetes-tests, skip-openshift-tests
