Repository uselagoon/lagoon, pull requests merged in 2021-06, with the labels that each got.

#2689 Bump CI tool versions to latest stable
  Makefile
Labels: 6-images-testing

#2688 Removing Billing from UI
  services/ui/server.js
  services/ui/src/components/BillingGroup/data.json
  services/ui/src/components/BillingGroup/index.js
  services/ui/src/components/BillingGroup/index.stories.js
  services/ui/src/components/BillingGroupBarChart/data.json
  services/ui/src/components/BillingGroupBarChart/index.js
  services/ui/src/components/BillingGroupBarChart/index.stories.js
  services/ui/src/components/BillingGroupInvoice/index.js
  services/ui/src/components/BillingGroupProjects/ClusterName.js
  services/ui/src/components/BillingGroupProjects/data.json
  services/ui/src/components/BillingGroupProjects/index.js
  services/ui/src/components/BillingGroupProjects/index.stories.js
  services/ui/src/components/BillingGroups/index.js
  services/ui/src/components/BillingGroups/index.stories.js
  services/ui/src/components/BillingModifiers/AddBillingModifier.js
  services/ui/src/components/BillingModifiers/AllBillingModifiers.js
  services/ui/src/components/BillingModifiers/BillingModifierForm.js
  services/ui/src/components/BillingModifiers/data.json
  services/ui/src/components/BillingModifiers/index.stories.js
  services/ui/src/components/link/BillingGroup.js
  services/ui/src/lib/Authenticator.js
  services/ui/src/lib/fragment/BillingModifier.js
  services/ui/src/lib/mutation/AddBillingModifier.js
  services/ui/src/lib/mutation/AddProjectToBillingGroup.js
  services/ui/src/lib/mutation/DeleteBillingModifier.js
  services/ui/src/lib/mutation/UpdateBillingModifier.js
  services/ui/src/lib/mutation/UpdateProjectBillingGroup.js
  services/ui/src/lib/query/AllBillingGroups.js
  services/ui/src/lib/query/AllBillingModifiers.js
  services/ui/src/lib/query/BillingGroupCosts.js
  services/ui/src/lib/query/BillingProjectByName.js
  services/ui/src/pages/admin/billing-projects-not-in-group.js
  services/ui/src/pages/admin/billing.js
  services/ui/src/pages/admin/index.js
  services/ui/src/pages/admin/overrides.css
  services/ui/src/pages/admin/projects.js
  services/ui/src/pages/stories/admin.stories.js
Labels: 10-admin-user-interfaces

#2659 Adds async calls to parallelize Bitbucket groups syncs
  services/api/src/bitbucket-sync/repo-permissions.ts
Labels: lagoon-one

#2685 Backporting Harbor fixes to master
  services/api/Dockerfile
  services/api/src/clients/harborClient.js
  services/api/src/migrations/2-harbor/harborSync.ts
  services/api/src/resources/project/harborSetup.ts
Labels: 2-build-deploy, 8-automation-helpers

#2719 Avoid helm installing the registry twice in kind/test
  Makefile
Labels: 6-images-testing

#2715 Wait for kind control plane
  Makefile
Labels: 6-images-testing

#2713 Simplify retest logic
  Makefile
Labels: 6-images-testing

#2716 Split out some more of the features-kubernetes tests
  Makefile
  tests/tests/features-api-variables.yaml
  tests/tests/features-kubernetes.yaml
Labels: 6-images-testing

#2727 Allow the make jobserver to co-ordinate with sub-makes
  Makefile
Labels: 6-images-testing

#2729 Parameterise the kind/push-images Makefile target
  Makefile
Labels: 6-images-testing

#2728 Fix duplicate lagoon-tests installed in local test cluster
  Makefile
Labels: 6-images-testing

#2731 Remove some sleeps from test suite
  Makefile
Labels: 6-images-testing

#2732 Don't scan images by default in build/* Makefile targets
  Jenkinsfile
  Makefile
Labels: 6-images-testing
