Repository uselagoon/lagoon, pull requests merged in 2022-02, with the labels that each got.

#2974 Resolving alertmanager config creation bug
  node-packages/commons/src/tasks.ts
Labels: 4-metrics-alerting, 2-build-deploy, needs-tests

#2381 Add middleware for security headers.
  services/ui/server.js
Labels: 10-admin-user-interfaces, 9-security

#3043 fix: handle symlink to charts directory other than a local subdirectory
  Makefile
Labels: 6-images-testing

#3042 feat: add configuration-complete readiness signalling to keycloak
  services/keycloak/start.sh
Labels: 0-kubernetes

#3034 Add cluster permission to allow downloading of reports from Kibana
  services/api/src/resources/group/opendistroSecurity.ts
Labels: bug, priority-high, 3-logging-reporting
