Repository uselagoon/lagoon, pull requests merged in 2022-08, with the labels that each got.

#3233 fix: add custom dnsConfig to all cronjobs
  images/kubectl-build-deploy-dind/helmcharts/basic-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/basic/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/cli/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/elasticsearch/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/kibana/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/logstash/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/mariadb-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/mongodb-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx-php/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/nginx/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/node-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/node/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/postgres-single/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/python-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/python/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/rabbitmq/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/redis/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/solr/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/varnish/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/worker-persistent/templates/cronjob.yaml
  images/kubectl-build-deploy-dind/helmcharts/worker/templates/cronjob.yaml
Labels: 0-kubernetes

#3074 chore: remove random wait from test suite
  tests/tests/active-standby-kubernetes.yaml
  tests/tests/active-standby-openshift.yaml
  tests/tests/api.yaml
  tests/tests/bitbucket.yaml
  tests/tests/bulk-deployment.yaml
  tests/tests/dbaas.yaml
  tests/tests/deploytarget.yaml
  tests/tests/drupal-php74.yaml
  tests/tests/drupal-php80.yaml
  tests/tests/drupal-postgres.yaml
  tests/tests/drush.yaml
  tests/tests/elasticsearch.yaml
  tests/tests/features-api-variables.yaml
  tests/tests/features-kubernetes-2.yaml
  tests/tests/features-kubernetes.yaml
  tests/tests/features-openshift.yaml
  tests/tests/features/random-wait.yaml
  tests/tests/generic.yaml
  tests/tests/github.yaml
  tests/tests/gitlab.yaml
  tests/tests/image-cache.yaml
  tests/tests/nginx.yaml
  tests/tests/node-mongodb.yaml
  tests/tests/node-various.yaml
  tests/tests/node.yaml
  tests/tests/python.yaml
  tests/tests/ssh-portal.yaml
  tests/tests/tasks.yaml
  tests/tests/workflows.yaml
Labels: 6-images-testing

#3226 Chore: remove logs2logs-db
  node-packages/commons/src/local-logging.ts
  services/logs2logs-db/Dockerfile
  services/logs2logs-db/certs/lumberjack.cert
  services/logs2logs-db/certs/lumberjack.key
  services/logs2logs-db/entrypoints/90-logstash-enable-forward-external-logstash.sh
  services/logs2logs-db/pipeline/debug.conf
  services/logs2logs-db/pipeline/lagoon-logs.conf
  services/logs2logs-db/pipeline/router-application-logs.conf
  services/logs2logs-db/pipeline/service-logs.conf
  services/logs2logs-db/pipelines.yml
  services/logs2logs-db/templates/application-logs.json
  services/logs2logs-db/templates/lagoon-logs.json
  services/logs2logs-db/templates/router-logs.json
  services/logs2logs-db/templates/service-logs.json
Labels: vestigial

#3261 Feature: return error if environments exist when deleting project
  services/api/src/resources/project/resolvers.ts
  services/api/src/resources/project/sql.ts
  tests/tasks/api/delete-project.yaml
Labels: 1-api-auth
